### ISSUE TITLE
Can't Load Autodrive Config

### ISSUE THREAD

**Issue by BeastyBass** [KillBait/AutoDrive_Course_Editor#1]
When I press "File" an then "Load Config" only a white Window is showin.

![image](https://user-images.githubusercontent.com/64255382/146652017-86bc2d85-b461-45c1-8db4-ca339f50ef30.png)

**Comment by KillBait** [comment]
That's a very strange lockup.. could you attach the AutoDriveEditor.log here, so i can take a look and see what is going on.

Thanks for the report

**Comment by BeastyBass** [comment]
> 

The file is empty

**Comment by BeastyBass** [comment]
> That's a very strange lockup.. could you attach the AutoDriveEditor.log here, so i can take a look and see what is going on.
> 
> Thanks for the report

It was my mistake. After I copy it in to "My Games/FarmingSimulator2022" it worked

**Comment by BeastyBass** [comment]
> > That's a very strange lockup.. could you attach the AutoDriveEditor.log here, so i can take a look and see what is going on.
> > Thanks for the report
> 
> It was my mistake. After I copy it in to "My Games/FarmingSimulator2022" it worked

Ok after i start the program again, the white window is back

**Comment by KillBait** [comment]
Rearly odd.. try [this](https://github.com/KillBait/AutoDrive_Course_Editor/raw/master/AutoDriveEditor.jar) version of the editor and see if that fixes it

**Comment by BeastyBass** [comment]
> Rearly odd.. try [this](https://github.com/KillBait/AutoDrive_Course_Editor/raw/master/AutoDriveEditor.jar) version of the editor and see if that fixes it

Yes this version is working. Thank you.
