### ISSUE TITLE
Cut&Paste moves and duplicates content

### ISSUE THREAD

**Issue by AdmiralDan** [KillBait/AutoDrive_Course_Editor#16]
If you use Cut&Paste the pasted version will be moved. If you use Cut&Paste more than once, a queue is formed and all already copied versions are pasted again and also moved

https://user-images.githubusercontent.com/96954402/147858238-809025d3-bd09-4827-8a48-abec3cc63f9e.mp4

.

**Comment by KillBait** [comment]
That is one odd bug :) , i just fixed it, will be available in next release.

Thanks for the report
