### ISSUE TITLE
PDA will not load

### ISSUE THREAD

**Issue by Knowen** [KillBait/AutoDrive_Course_Editor#17]
Hello,

I'm playing on the North Dakota Hastings 16x Map in FS22 and trying to edit the course with the editor. Somehow the PDA map cant be loaded.
Is the format wrong? filetype or size?

Attached is the PDA.dds and the autodrive_config
[Issue Data.zip](https://github.com/KillBait/AutoDrive_Course_Editor/files/7798903/Issue.Data.zip)

Best regards,
Knowen

**Comment by KillBait** [comment]
It was the wrong size, i've uploaded the correct image to my other repository, the editor should automatically download it the next time you open the config.

**Comment by Knowen** [comment]
Thank you!
