### ISSUE TITLE
[ Query ] Best Practice to cut and paste Production loops from one map to another map

### ISSUE THREAD

**Issue by BullFlag** [KillBait/AutoDrive_Course_Editor#22]
Best Practice to copy and paste AD Production Routes between two maps?

I have an excellent AD for Elmcreek Base-game Map ( has all production waypoint loops )  want to cut and paste these into another  AD for Elmcreek Edit by Stevie v2 ( missing many production waypoint loops)

How would you approach this given I have this amazing AD editor?  What is the best practices you would recommend?    Just installed editor yesterday  and and had zero issues getting it going, the User Interface design / experience looks pro.

Screen shot of the new fields and expanded Farm Yard by Stevie on Elmcreek.    SE corner is where the changes where made,   but AD missing many production loops.

![Elmcreek_Edit_by_Stevie_](https://user-images.githubusercontent.com/23723361/148230668-5483cfe9-0a9e-4665-ba4d-c5278e1af48c.png)

**Comment by KillBait** [comment]
In theory you can copy any part of the network load another config and
paste it straight  into that one, the only downside to this is you will
have to move the pasted nodes into the correct position.

Paste into the original place is something I have yet to add to the editor,
but it is on my list of things to do.

Good to hear you find it useful

**Comment by BullFlag** [comment]
Yes, the tricky part for me was guessing where the pasted route clipping would be positioned.

I believe the "Center of the Clipping" is where the paste operation drops the route object down.    It is hard
guess where the "Center point" would be 

What if a "paste-here" mark was automatically created on one straight boundary segment.    That could show where the cursor places one specific route segment.   Likely there's a simpler than this.    

Did I miss where the pasted point is?

![Cut and Paste](https://user-images.githubusercontent.com/23723361/148412652-fb3ec680-f317-4972-bbb0-87419b777980.png)

**Comment by yann-mrt** [comment]
I agree this is something that could be very helpful !! I try today to make copy paste between 2 config and with the undo function i could manage but it was not easy.

**Comment by KillBait** [comment]
I agree, it's not ideal for this sort of scenario, but,  i'm working on a paste in place now, should be out in the next version.

Sorry for the delay in replying, new job and RL means not much time to look into this.

**Comment by KillBait** [comment]
Forgot to explain what paste in place means, it's simply paste in the original map location it was copied from

**Comment by BullFlag** [comment]
I like this cleaver solution.      You'll keep the coordinates the same between maps.  
   
Crazy idea, On the same map "teleport the object" using coordinate number entry   ( Crazy ALiEN Jim author of  Tardis )

**Comment by KillBait** [comment]
i just pushed V0.70.0 to release, the paste-in-place is included, any issues with it, let me know.

> Crazy idea, On the same map "teleport the object" using coordinate number entry

You can enable debug mode, in it is a option to show all the nodes ID and goto node ID option

**Comment by BullFlag** [comment]
WOW the paste-in-place worker perfectly....
![copy_and_keep_coordinates](https://user-images.githubusercontent.com/23723361/148663160-8793bf41-7b29-46be-856f-c4e8a308d64b.png)
l

**Comment by BullFlag** [comment]
Great work
