### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by yann-mrt** [KillBait/AutoDrive_Course_Editor#23]
Good day,

Could be possible to have an auto saving done for the config. Because after working for more than 50min and course editor hand, it's hurting. 
_I know I should save the file more often_

**Any way to recover some part of my work ??**

BTW, the work you done for this auto course is really amazing. From one program that was working but without much option you did some thing that now have purpose. 
GREAT Job and thanks for your time !!!

Thanks
Yann

**Comment by KillBait** [comment]
I agree, it's something that has been on my to-do list,  i'm working on something related to making a backup file, so it's not a big deal to add this in at the same time. I'm currently working with a max of 10 backups, with a default time interval of
10 minutes. Of course i've made the time interval an option you can change

I would like an option if you have time

Should the backup files be saved in the same folder as the config? or in a 'Backup" sub folder

For example:

If the config location is C:/ExampleConfig/AutoDrive_config.xml, should the backup be placed in

    C:/ExampleConfig/AutoDrive_config_backup_1-10.xml

or

     C:/ExampleConfig/Backups/AutoDrive_config_backup_1-10.xml 

Sorry for the delay in replying, new job and RL means not much time to look into this at the moment.

**Comment by yann-mrt** [comment]
For me I would prefer in the same folder.

As well any way to keep the last  C:/ExampleConfig in memory/default when opening or save new file? It is always come back to "my documents" and obviously my course editor working folder is not there.

**Comment by KillBait** [comment]
That is possible, i could save the last config file loaded in the editors config file and re-use that on running the editor to set the default folder

**Comment by yann-mrt** [comment]
That nice.
It their is any way to recover some work from a 50 MN work that end with the hang of the course editor (problem stipulate in the hang post). I still didn't close anything yet.

**Comment by KillBait** [comment]
i just pushed V0.70.0 to release, the  autosave is included, any issues with it, let me know

**Comment by yann-mrt** [comment]
Work well for me, thanks you.
Just to keep in mind the when you reopen course editor the old save file are still kept. so Course editor will save on the top of the old ones without warning or asking. I don't think it is a major problem, at least for me. but it is good to know.
![image](https://user-images.githubusercontent.com/74056604/148768986-9eb631fc-2b43-41af-aa7f-a4ee4e01f4b2.png)

**Comment by yann-mrt** [comment]
Ok and after 10 saving files what will happen ?

**Comment by KillBait** [comment]
Yeah, it just makes sure the oldest save is always overwritten
