### ISSUE TITLE
heightmap import

### ISSUE THREAD

**Issue by velendier** [KillBait/AutoDrive_Course_Editor#27]
wile in editor i am trying to import an heightmap it is greyed out and dose not allow me to select it. am i doing something wrong.

**Comment by KillBait** [comment]
nope, i started to add that feature and got side tracked onto other things, it will be added in the day or two.

The workaround until then is, copy the 'terrain.heightmap.png' for the map into the same place as the config
and the editor should load it.

**Comment by KillBait** [comment]
v0.70.1 has this working now..

**Comment by velendier** [comment]
holy crap man thanks i go to bed and wake up with it working. great job, i am new to autodrive never used it before fs22. but this editor is awesome man thanks.
