### ISSUE TITLE
Less nodes on straight routes

### ISSUE THREAD

**Issue by gfa4711** [KillBait/AutoDrive_Course_Editor#33]
Hi

first of all thank you for the cool tool.

At the moment I play the Big River x16 map and I started to use your tool to speed up the process of building courses.
This works very fine, but for my opinion the tool creates to many nodes for straight lines.
At the top of the screenshot you can see the points from the Course Editor, at the bottom those from Autodrive.

![image](https://user-images.githubusercontent.com/53525488/149905952-03df9769-1b6d-4640-9a63-05fe8c01ee5e.png)

On smaller maps it certainly doesn't make a difference, but on a 16x map the number of points is enormous.
Is there a way to reduce the number of points between two nodes when connecting them?
If not, could you include a slider to control that, for example?

Have a nice day!

**Comment by KillBait** [comment]
Yeah, liner lines will scale the number of nodes the higher the zoom level is, but that isn't correct, a temp workaround it to
edit the <LinearLineNodeDistance>12</LinearLineNodeDistance> option in the editor config ( EditorConfig.xml ). 

Try setting the node distance to 48 and that should reduce the number down to a reasonable level. If you later on edit
a different map, don't forget to change the distance back down.

Thanks for the report, i'll get that fixed for the next version..

**Comment by gfa4711** [comment]
Ok, thx for the info, I will try it.
