### ISSUE TITLE
There are no pda_map_H.dds files for FS22

### ISSUE THREAD

**Issue by adampawelec** [KillBait/AutoDrive_Course_Editor#4]
Hey! I'm trying to use the editor to edit Haut-Beyleron but I obviously need the background map. I get the windows with the tip of using the pda_map_H.dds file from the maps folder, but looks like they dont exist for the three default maps. There's the overview.dds file but it's the wrong size so the roads dont line up.

**Comment by KillBait** [comment]
You can use the "Maps -> Import FS22 PDA Image" menu option to convert the overview.dds, dont forget too use the "Map -> Save Imported Image" option to save the image for use later on.

The logic behind the pda_map_H.dds dialog doesnt take into account v2 of Autodrive, i'm fixing that now

**Comment by KillBait** [comment]
you can get the correct map images from my other repository [here](https://github.com/KillBait/FS19_AutoDrive_MapImages/tree/main/mapImages)

**Comment by c0nnex** [comment]
Anyone edited the map to already include "shading" of the standard fields?
I want to smooth my AD courses, and draw field-sub-courses but on the map in the other repo (or overview.dds) the fields are not visible, so it taks a long time to draw the sub-course, reload fs22 just to see that the course will cut into the (standard) field and not stay on the surrounding area
