### ISSUE TITLE
Map Elk Mountain Wyoming can`t be open

### ISSUE THREAD

**Issue by Maag000** [KillBait/AutoDrive_Course_Editor#42]
Hello,
if I will open the overview.dds from the Elk Mountain Wyoming map I get the Error "GlobalExceptionHandler - Java heap space
java.lang.OutOfMemoryError: Java heap space" in the log and the map will not shown in the editor.
What`s wrong with it?

**Comment by KillBait** [comment]
Hi,

That is one stupidly huge DDS file!!, I have uploaded the converted images to the map Images GitHub,
so the editor should download the images next time you load a config for that map.

As for the Out of memory error, just loading in that DDS file and converting it raised the memory
usage of the editor to just over 2.5GB! :/

![Screenshot_Elk_Mountain_import](https://user-images.githubusercontent.com/7914589/169830797-2bedde4b-4ba8-4d15-b512-4d9be78c406e.png)

just loading the config with the converted images gives the usual memory usage.

![Screenshot_Elk_Mountain_normal](https://user-images.githubusercontent.com/7914589/169830989-8756596e-b131-4023-981d-cf3d157d5b14.png)

If you ever run into the out of heap memory again, try raising the -Xmx memory in the launch script, i had
to set it to -Xmx3072m to  get the DDS file to import and convert

**Comment by Maag000** [comment]
Best man, thank you!!!
